ECO-1043 missing fields for addresses
spryker-eco/arvato-rss pull request #12
Opened 2018-01-10 13:56 UTC by aleksey-kotsuba

- Developer(s): @aleksey-kotsuba

- Peer Reviewer:

- Ticket: https://spryker.atlassian.net/browse/ECO-1041

- Project PR: https://github.com/spryker-eco/arvato-rss

- Academy PR:

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department
- [ ] All new or heavily changed classes get an "A" rating (Scrutinizer), except Facades, Factories, QueryContainers and Tests

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   ArvatoRss             | patch (new)           |                       |

#### Release Notes

-----------------------------------------

#### Module ArvatoRss

_**Patch:** Backwards-compatible bug fix_

Def of done (by responsible developer):
- [ ] All changes are backward-compatible. Outdated code is marked as deprecated.
- [ ] The change is isolated and not mixed with any cleanups or other changes.
- [ ] New code fits to the architecture rules.
- [ ] All new or changed business logic is covered by functional tests (in Zed business layer).

##### Change log

### Bugfixes
Additional Address field has been mapped to request and processed from response.

2018-01-12 10:05 UTC, jandert requested changes
Please add a test for this:
1. Response with this additional field set
2. without the additional field

2018-01-12 10:05 UTC, jandert commented on src/SprykerEco/Zed/ArvatoRss/Business/Api/Converter/RiskCheckResponseConverter.php
> +        $addressValidationResponse->setStreetNumberAdditional($response->StreetNumberAdditional);
check for existence. Field doesn't have to be there.

2018-01-12 10:07 UTC, profuel requested changes
Please update functional/unit tests to cover added functionality

2018-01-12 10:07 UTC, profuel commented on src/SprykerEco/Zed/ArvatoRss/Business/Api/ArvatoRssRequestApiConfig.php
> +    const ARVATORSS_API_STREET_ADDITIONAL = 'StreetNumberAdditional';
Not logical name, I would include NUMBER as well in constant name

2018-01-15 13:36 UTC, jandert commented on src/SprykerEco/Zed/ArvatoRss/Business/Api/ArvatoRssRequestApiConfig.php
> +    const ARVATORSS_API_STREET_ADDITIONAL = 'StreetNumberAdditional';
Does not have to a number. Could also say smt like "2nd floor" or so

2018-01-17 08:32 UTC, profuel approved these changes

2018-01-17 08:42 UTC, jandert approved these changes

2018-01-17 08:59 UTC, merged