ECO-1044: Only send delivery address, when its different from billing address
spryker-eco/arvato-rss pull request #13
Opened 2018-01-11 10:04 UTC by aleksey-kotsuba

- Developer(s): @aleksey-kotsuba

- Peer Reviewer:

- Ticket: https://spryker.atlassian.net/browse/ECO-1044

- Project PR: https://github.com/spryker-eco/arvato-rss

- Academy PR:

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department
- [ ] All new or heavily changed classes get an "A" rating (Scrutinizer), except Facades, Factories, QueryContainers and Tests

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   ArvatoRss             | patch (new)           |                       |

#### Release Notes

-----------------------------------------

#### Module ArvatoRss

_**Patch:** Backwards-compatible bug fix_

Def of done (by responsible developer):
- [ ] All changes are backward-compatible. Outdated code is marked as deprecated.
- [ ] The change is isolated and not mixed with any cleanups or other changes.
- [ ] New code fits to the architecture rules.
- [ ] All new or changed business logic is covered by functional tests (in Zed business layer).

##### Change log

### Bugfixes
Check for equal billing and shipping address has been added.
Only Billing address send if it's equal to shipping.

2018-01-12 09:49 UTC, profuel commented
I don't see unit/functional tests updated for this functionality.

2018-01-12 10:01 UTC, jandert approved these changes

2018-01-15 12:17 UTC, profuel requested changes

2018-01-15 12:17 UTC, profuel commented on tests/SprykerEcoTest/Zed/ArvatoRss/Business/Api/Converter/RiskCheckRequestConverterTest.php
> +        $result = $converter->convert($requestTransfer);
you have this variable before calling this function, please reuse value.

2018-01-15 12:17 UTC, profuel commented on tests/SprykerEcoTest/Zed/ArvatoRss/Business/Api/Converter/RiskCheckRequestConverterTest.php
> +        $requestTransfer = (new ArvatoRssRiskCheckRequestBuilder())
Please create separate tests.
Each test should test one case/function.
Consider 'dataProvider' usage in case the code is similar

2018-01-15 12:17 UTC, profuel commented on tests/SprykerEcoTest/Zed/ArvatoRss/Business/Api/Converter/RiskCheckResponseConverterTest.php
> +    protected function testDeliveryPresents(RiskCheckResponseConverter $converter)
Same, please create separate tests

2018-01-15 12:17 UTC, profuel commented on tests/SprykerEcoTest/Zed/ArvatoRss/Business/Api/Converter/RiskCheckResponseConverterTest.php
> +        $response = $this->createResponseWithBilling();
Please create function with code
```
 +        $response = $this->createResponse();
 +        $response->Details = new stdClass();
 +        $response->Details->BillingCustomerResult = new stdClass();
 +        $response->Details->BillingCustomerResult->ServiceResults = new stdClass();```
and reuse it, with such 'override' calls you may get unexpected results for some internal properties.

2018-01-15 12:17 UTC, profuel commented on tests/SprykerEcoTest/Zed/ArvatoRss/Business/Api/Converter/RiskCheckResponseConverterTest.php
> +        $response = $this->createResponseWithBilling();
If you need to add different data, please create functions like 'addBillingTestData', 'addDeliveryTestData', etc and call them one after another when required.

2018-01-15 12:17 UTC, profuel commented on tests/SprykerEcoTest/Zed/ArvatoRss/Business/Api/Mapper/RiskCheckRequestMapperTest.php
> +        $this->quote->setBillingSameAsShipping(true);
Same here  - 2 tests in one call

2018-01-15 13:07 UTC, profuel commented on tests/SprykerEcoTest/Zed/ArvatoRss/Business/Api/Mapper/RiskCheckRequestMapperTest.php
> +        $this->assertInstanceOf(ArvatoRssDeliveryCustomerTransfer::class, $result->getDeliveryCustomer());
Please think of more detailed verification here, if required.

2018-01-17 12:15 UTC, profuel commented on tests/SprykerEcoTest/Zed/ArvatoRss/Business/Api/Mapper/RiskCheckRequestMapperTest.php
> +        $this->assertNotEquals($quote->getBillingSameAsShipping(), (bool) $result->getDeliveryCustomer());
please use more clear check `$result->getDeliveryCustomer() !== null`

2018-01-17 12:54 UTC, profuel approved these changes

2018-01-17 12:54 UTC, merged