ECO-1042 StoreOrderRequestMapper is mapping idCustomer instead of customerReference
spryker-eco/arvato-rss pull request #9
Opened 2018-01-09 11:22 UTC by aleksey-kotsuba

DebitorNumber field in ArvatoRssOrderTransfer has been mapped to customerReference instead of idCustomer.

2018-01-10 08:05 UTC, anton-kiva approved these changes

2018-01-12 10:08 UTC, jandert approved these changes

2018-01-12 10:08 UTC, profuel requested changes
Please cover this with unit/functional tests

2018-01-15 12:11 UTC, profuel approved these changes

2018-01-16 10:11 UTC, merged